name: iOS starter workflow

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Testing
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'

      - name: List available simulators (debug)
        run: xcrun simctl list devices

      - name: Run Tests
        run: |
          xcodebuild test \
            -scheme 'ParrotIos' \
            -destination 'platform=iOS Simulator,OS=18.1,type=iPhone'
