name: iOS starter workflow

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build and Test default scheme using any iPhone simulator with iOS version 18.0 or newer
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1

      - name: Run Tests
        run: |
          xcodebuild test \
            -scheme 'ParrotIos' \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.1'
