name: CI Pipeline

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Testing
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'

      - name: Run Tests
        run: |
          if xcodebuild -scheme ParrotIos -showdestinations | grep -q 'OS:18.1, name:iPhone 15'; then
            name='iPhone 15'
          else
            name='iPhone 16'
          fi
          xcodebuild test \
            -scheme 'ParrotIos' \
            -destination "platform=iOS Simulator,name=$name,OS=18.1" \
            -skipPackagePluginValidation
