name: iOS Build & Test

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Set Default Scheme
        run: |
          scheme=$(xcodebuild -list -json | jq -r '.project.schemes[0]')
          echo "SCHEME=$scheme" >> $GITHUB_ENV
          echo "Using scheme: $scheme"

      - name: Find Available iPhone Simulator
        run: |
          device_info=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*\(([A-F0-9\-]+)\)')
          if [ -z "$device_info" ]; then
            echo "No available iPhone Simulator found!" && exit 1
          fi
          device_uuid=$(echo "$device_info" | head -1 | awk -F '[()]' '{print $2}')
          echo "DEVICE_UUID=$device_uuid" >> $GITHUB_ENV
          echo "Using simulator: $device_uuid"

      - name: Reset and Boot Simulator
        run: |
          xcrun simctl shutdown all
          xcrun simctl erase all
          xcrun simctl boot $DEVICE_UUID

      - name: Clean Derived Data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Detect Project Type
        run: |
          if ls -A | grep -iE '\.xcworkspace$' >/dev/null; then
            echo "FILETYPE_PARAMETER=workspace" >> $GITHUB_ENV
            echo "FILE_TO_BUILD=$(ls -A | grep -iE '\.xcworkspace$')" >> $GITHUB_ENV
          else
            echo "FILETYPE_PARAMETER=project" >> $GITHUB_ENV
            echo "FILE_TO_BUILD=$(ls -A | grep -iE '\.xcodeproj$')" >> $GITHUB_ENV
          fi

      - name: Build for Testing
        run: |
          xcodebuild build-for-testing \
            -scheme "$SCHEME" \
            -$FILETYPE_PARAMETER "$FILE_TO_BUILD" \
            -destination "id=$DEVICE_UUID"

      - name: Run Tests
        run: |
          xcodebuild test-without-building \
            -scheme "$SCHEME" \
            -$FILETYPE_PARAMETER "$FILE_TO_BUILD" \
            -destination "id=$DEVICE_UUID"
